// Code generated by Wire protocol buffer compiler, do not edit.
// Source: niconicobulletcomments.BulletComment in NicoNicoBulletComments.proto
package org.schabi.newpipe.extractor.services.niconico.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.ReverseProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Integer;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import java.util.List;
import java.util.Objects;
import okio.ByteString;

public final class BulletComment extends Message<BulletComment, BulletComment.Builder> {
  public static final ProtoAdapter<BulletComment> ADAPTER = new ProtoAdapter_BulletComment();

  private static final long serialVersionUID = 0L;

  @WireField(
      tag = 1,
      adapter = "org.schabi.newpipe.extractor.services.niconico.protobuf.BulletComment$MessageItem#ADAPTER",
      label = WireField.Label.REPEATED
  )
  public final List<MessageItem> items;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.OMIT_IDENTITY,
      jsonName = "backwardUrl"
  )
  public final String backward_url;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.OMIT_IDENTITY,
      jsonName = "snapshotUrl"
  )
  public final String snapshot_url;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.REPEATED
  )
  public final List<String> segments;

  public BulletComment(List<MessageItem> items, String backward_url, String snapshot_url,
      List<String> segments) {
    this(items, backward_url, snapshot_url, segments, ByteString.EMPTY);
  }

  public BulletComment(List<MessageItem> items, String backward_url, String snapshot_url,
      List<String> segments, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.items = Internal.immutableCopyOf("items", items);
    if (backward_url == null) {
      throw new IllegalArgumentException("backward_url == null");
    }
    this.backward_url = backward_url;
    if (snapshot_url == null) {
      throw new IllegalArgumentException("snapshot_url == null");
    }
    this.snapshot_url = snapshot_url;
    this.segments = Internal.immutableCopyOf("segments", segments);
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.items = Internal.copyOf(items);
    builder.backward_url = backward_url;
    builder.snapshot_url = snapshot_url;
    builder.segments = Internal.copyOf(segments);
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof BulletComment)) return false;
    BulletComment o = (BulletComment) other;
    return unknownFields().equals(o.unknownFields())
        && items.equals(o.items)
        && Internal.equals(backward_url, o.backward_url)
        && Internal.equals(snapshot_url, o.snapshot_url)
        && segments.equals(o.segments);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + items.hashCode();
      result = result * 37 + (backward_url != null ? backward_url.hashCode() : 0);
      result = result * 37 + (snapshot_url != null ? snapshot_url.hashCode() : 0);
      result = result * 37 + segments.hashCode();
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (!items.isEmpty()) builder.append(", items=").append(items);
    if (backward_url != null) builder.append(", backward_url=").append(Internal.sanitize(backward_url));
    if (snapshot_url != null) builder.append(", snapshot_url=").append(Internal.sanitize(snapshot_url));
    if (!segments.isEmpty()) builder.append(", segments=").append(Internal.sanitize(segments));
    return builder.replace(0, 2, "BulletComment{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<BulletComment, Builder> {
    public List<MessageItem> items;

    public String backward_url;

    public String snapshot_url;

    public List<String> segments;

    public Builder() {
      items = Internal.newMutableList();
      backward_url = "";
      snapshot_url = "";
      segments = Internal.newMutableList();
    }

    public Builder items(List<MessageItem> items) {
      Internal.checkElementsNotNull(items);
      this.items = items;
      return this;
    }

    public Builder backward_url(String backward_url) {
      this.backward_url = backward_url;
      return this;
    }

    public Builder snapshot_url(String snapshot_url) {
      this.snapshot_url = snapshot_url;
      return this;
    }

    public Builder segments(List<String> segments) {
      Internal.checkElementsNotNull(segments);
      this.segments = segments;
      return this;
    }

    @Override
    public BulletComment build() {
      return new BulletComment(items, backward_url, snapshot_url, segments, super.buildUnknownFields());
    }
  }

  public static final class MessageItem extends Message<MessageItem, MessageItem.Builder> {
    public static final ProtoAdapter<MessageItem> ADAPTER = new ProtoAdapter_MessageItem();

    private static final long serialVersionUID = 0L;

    @WireField(
        tag = 1,
        adapter = "org.schabi.newpipe.extractor.services.niconico.protobuf.BulletComment$MessageItem$Meta#ADAPTER",
        label = WireField.Label.OMIT_IDENTITY
    )
    public final Meta meta;

    @WireField(
        tag = 2,
        adapter = "org.schabi.newpipe.extractor.services.niconico.protobuf.BulletComment$MessageItem$Message#ADAPTER",
        label = WireField.Label.OMIT_IDENTITY
    )
    public final Message message;

    public MessageItem(Meta meta, Message message) {
      this(meta, message, ByteString.EMPTY);
    }

    public MessageItem(Meta meta, Message message, ByteString unknownFields) {
      super(ADAPTER, unknownFields);
      this.meta = meta;
      this.message = message;
    }

    @Override
    public Builder newBuilder() {
      Builder builder = new Builder();
      builder.meta = meta;
      builder.message = message;
      builder.addUnknownFields(unknownFields());
      return builder;
    }

    @Override
    public boolean equals(Object other) {
      if (other == this) return true;
      if (!(other instanceof MessageItem)) return false;
      MessageItem o = (MessageItem) other;
      return unknownFields().equals(o.unknownFields())
          && Internal.equals(meta, o.meta)
          && Internal.equals(message, o.message);
    }

    @Override
    public int hashCode() {
      int result = super.hashCode;
      if (result == 0) {
        result = unknownFields().hashCode();
        result = result * 37 + (meta != null ? meta.hashCode() : 0);
        result = result * 37 + (message != null ? message.hashCode() : 0);
        super.hashCode = result;
      }
      return result;
    }

    @Override
    public String toString() {
      StringBuilder builder = new StringBuilder();
      if (meta != null) builder.append(", meta=").append(meta);
      if (message != null) builder.append(", message=").append(message);
      return builder.replace(0, 2, "MessageItem{").append('}').toString();
    }

    public static final class Builder extends com.squareup.wire.Message.Builder<MessageItem, Builder> {
      public Meta meta;

      public Message message;

      public Builder() {
      }

      public Builder meta(Meta meta) {
        this.meta = meta;
        return this;
      }

      public Builder message(Message message) {
        this.message = message;
        return this;
      }

      @Override
      public MessageItem build() {
        return new MessageItem(meta, message, super.buildUnknownFields());
      }
    }

    public static final class Meta extends com.squareup.wire.Message<Meta, Meta.Builder> {
      public static final ProtoAdapter<Meta> ADAPTER = new ProtoAdapter_Meta();

      private static final long serialVersionUID = 0L;

      @WireField(
          tag = 1,
          adapter = "com.squareup.wire.ProtoAdapter#STRING",
          label = WireField.Label.OMIT_IDENTITY
      )
      public final String id;

      @WireField(
          tag = 2,
          adapter = "org.schabi.newpipe.extractor.services.niconico.protobuf.BulletComment$MessageItem$Meta$Timestamp#ADAPTER",
          label = WireField.Label.OMIT_IDENTITY
      )
      public final Timestamp timestamp;

      @WireField(
          tag = 3,
          adapter = "org.schabi.newpipe.extractor.services.niconico.protobuf.BulletComment$MessageItem$Meta$AdditionalInfo#ADAPTER",
          label = WireField.Label.OMIT_IDENTITY,
          jsonName = "additionalInfo"
      )
      public final AdditionalInfo additional_info;

      public Meta(String id, Timestamp timestamp, AdditionalInfo additional_info) {
        this(id, timestamp, additional_info, ByteString.EMPTY);
      }

      public Meta(String id, Timestamp timestamp, AdditionalInfo additional_info,
          ByteString unknownFields) {
        super(ADAPTER, unknownFields);
        if (id == null) {
          throw new IllegalArgumentException("id == null");
        }
        this.id = id;
        this.timestamp = timestamp;
        this.additional_info = additional_info;
      }

      @Override
      public Builder newBuilder() {
        Builder builder = new Builder();
        builder.id = id;
        builder.timestamp = timestamp;
        builder.additional_info = additional_info;
        builder.addUnknownFields(unknownFields());
        return builder;
      }

      @Override
      public boolean equals(Object other) {
        if (other == this) return true;
        if (!(other instanceof Meta)) return false;
        Meta o = (Meta) other;
        return unknownFields().equals(o.unknownFields())
            && Internal.equals(id, o.id)
            && Internal.equals(timestamp, o.timestamp)
            && Internal.equals(additional_info, o.additional_info);
      }

      @Override
      public int hashCode() {
        int result = super.hashCode;
        if (result == 0) {
          result = unknownFields().hashCode();
          result = result * 37 + (id != null ? id.hashCode() : 0);
          result = result * 37 + (timestamp != null ? timestamp.hashCode() : 0);
          result = result * 37 + (additional_info != null ? additional_info.hashCode() : 0);
          super.hashCode = result;
        }
        return result;
      }

      @Override
      public String toString() {
        StringBuilder builder = new StringBuilder();
        if (id != null) builder.append(", id=").append(Internal.sanitize(id));
        if (timestamp != null) builder.append(", timestamp=").append(timestamp);
        if (additional_info != null) builder.append(", additional_info=").append(additional_info);
        return builder.replace(0, 2, "Meta{").append('}').toString();
      }

      public static final class Builder extends com.squareup.wire.Message.Builder<Meta, Builder> {
        public String id;

        public Timestamp timestamp;

        public AdditionalInfo additional_info;

        public Builder() {
          id = "";
        }

        public Builder id(String id) {
          this.id = id;
          return this;
        }

        public Builder timestamp(Timestamp timestamp) {
          this.timestamp = timestamp;
          return this;
        }

        public Builder additional_info(AdditionalInfo additional_info) {
          this.additional_info = additional_info;
          return this;
        }

        @Override
        public Meta build() {
          return new Meta(id, timestamp, additional_info, super.buildUnknownFields());
        }
      }

      public static final class Timestamp extends com.squareup.wire.Message<Timestamp, Timestamp.Builder> {
        public static final ProtoAdapter<Timestamp> ADAPTER = new ProtoAdapter_Timestamp();

        private static final long serialVersionUID = 0L;

        @WireField(
            tag = 1,
            adapter = "com.squareup.wire.ProtoAdapter#INT64",
            label = WireField.Label.OMIT_IDENTITY
        )
        public final long seconds;

        @WireField(
            tag = 2,
            adapter = "com.squareup.wire.ProtoAdapter#INT32",
            label = WireField.Label.OMIT_IDENTITY
        )
        public final int nanos;

        public Timestamp(long seconds, int nanos) {
          this(seconds, nanos, ByteString.EMPTY);
        }

        public Timestamp(long seconds, int nanos, ByteString unknownFields) {
          super(ADAPTER, unknownFields);
          this.seconds = seconds;
          this.nanos = nanos;
        }

        @Override
        public Builder newBuilder() {
          Builder builder = new Builder();
          builder.seconds = seconds;
          builder.nanos = nanos;
          builder.addUnknownFields(unknownFields());
          return builder;
        }

        @Override
        public boolean equals(Object other) {
          if (other == this) return true;
          if (!(other instanceof Timestamp)) return false;
          Timestamp o = (Timestamp) other;
          return unknownFields().equals(o.unknownFields())
              && Internal.equals(seconds, o.seconds)
              && Internal.equals(nanos, o.nanos);
        }

        @Override
        public int hashCode() {
          int result = super.hashCode;
          if (result == 0) {
            result = unknownFields().hashCode();
            result = result * 37 + Long.hashCode(seconds);
            result = result * 37 + Integer.hashCode(nanos);
            super.hashCode = result;
          }
          return result;
        }

        @Override
        public String toString() {
          StringBuilder builder = new StringBuilder();
          builder.append(", seconds=").append(seconds);
          builder.append(", nanos=").append(nanos);
          return builder.replace(0, 2, "Timestamp{").append('}').toString();
        }

        public static final class Builder extends com.squareup.wire.Message.Builder<Timestamp, Builder> {
          public long seconds;

          public int nanos;

          public Builder() {
            seconds = 0L;
            nanos = 0;
          }

          public Builder seconds(long seconds) {
            this.seconds = seconds;
            return this;
          }

          public Builder nanos(int nanos) {
            this.nanos = nanos;
            return this;
          }

          @Override
          public Timestamp build() {
            return new Timestamp(seconds, nanos, super.buildUnknownFields());
          }
        }

        private static final class ProtoAdapter_Timestamp extends ProtoAdapter<Timestamp> {
          public ProtoAdapter_Timestamp() {
            super(FieldEncoding.LENGTH_DELIMITED, Timestamp.class, "type.googleapis.com/niconicobulletcomments.BulletComment.MessageItem.Meta.Timestamp", Syntax.PROTO_3, null, "NicoNicoBulletComments.proto");
          }

          @Override
          public int encodedSize(Timestamp value) {
            int result = 0;
            if (!Objects.equals(value.seconds, 0L)) {
              result += ProtoAdapter.INT64.encodedSizeWithTag(1, value.seconds);
            }
            if (!Objects.equals(value.nanos, 0)) {
              result += ProtoAdapter.INT32.encodedSizeWithTag(2, value.nanos);
            }
            result += value.unknownFields().size();
            return result;
          }

          @Override
          public void encode(ProtoWriter writer, Timestamp value) throws IOException {
            if (!Objects.equals(value.seconds, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 1, value.seconds);
            if (!Objects.equals(value.nanos, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.nanos);
            writer.writeBytes(value.unknownFields());
          }

          @Override
          public void encode(ReverseProtoWriter writer, Timestamp value) throws IOException {
            writer.writeBytes(value.unknownFields());
            if (!Objects.equals(value.nanos, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 2, value.nanos);
            if (!Objects.equals(value.seconds, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 1, value.seconds);
          }

          @Override
          public Timestamp decode(ProtoReader reader) throws IOException {
            Builder builder = new Builder();
            long token = reader.beginMessage();
            for (int tag; (tag = reader.nextTag()) != -1;) {
              switch (tag) {
                case 1: builder.seconds(ProtoAdapter.INT64.decode(reader)); break;
                case 2: builder.nanos(ProtoAdapter.INT32.decode(reader)); break;
                default: {
                  reader.readUnknownField(tag);
                }
              }
            }
            builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
            return builder.build();
          }

          @Override
          public Timestamp redact(Timestamp value) {
            Builder builder = value.newBuilder();
            builder.clearUnknownFields();
            return builder.build();
          }
        }
      }

      public static final class AdditionalInfo extends com.squareup.wire.Message<AdditionalInfo, AdditionalInfo.Builder> {
        public static final ProtoAdapter<AdditionalInfo> ADAPTER = new ProtoAdapter_AdditionalInfo();

        private static final long serialVersionUID = 0L;

        @WireField(
            tag = 1,
            adapter = "org.schabi.newpipe.extractor.services.niconico.protobuf.BulletComment$MessageItem$Meta$AdditionalInfo$InnerInfo#ADAPTER",
            label = WireField.Label.OMIT_IDENTITY,
            jsonName = "innerInfo"
        )
        public final InnerInfo inner_info;

        public AdditionalInfo(InnerInfo inner_info) {
          this(inner_info, ByteString.EMPTY);
        }

        public AdditionalInfo(InnerInfo inner_info, ByteString unknownFields) {
          super(ADAPTER, unknownFields);
          this.inner_info = inner_info;
        }

        @Override
        public Builder newBuilder() {
          Builder builder = new Builder();
          builder.inner_info = inner_info;
          builder.addUnknownFields(unknownFields());
          return builder;
        }

        @Override
        public boolean equals(Object other) {
          if (other == this) return true;
          if (!(other instanceof AdditionalInfo)) return false;
          AdditionalInfo o = (AdditionalInfo) other;
          return unknownFields().equals(o.unknownFields())
              && Internal.equals(inner_info, o.inner_info);
        }

        @Override
        public int hashCode() {
          int result = super.hashCode;
          if (result == 0) {
            result = unknownFields().hashCode();
            result = result * 37 + (inner_info != null ? inner_info.hashCode() : 0);
            super.hashCode = result;
          }
          return result;
        }

        @Override
        public String toString() {
          StringBuilder builder = new StringBuilder();
          if (inner_info != null) builder.append(", inner_info=").append(inner_info);
          return builder.replace(0, 2, "AdditionalInfo{").append('}').toString();
        }

        public static final class Builder extends com.squareup.wire.Message.Builder<AdditionalInfo, Builder> {
          public InnerInfo inner_info;

          public Builder() {
          }

          public Builder inner_info(InnerInfo inner_info) {
            this.inner_info = inner_info;
            return this;
          }

          @Override
          public AdditionalInfo build() {
            return new AdditionalInfo(inner_info, super.buildUnknownFields());
          }
        }

        public static final class InnerInfo extends com.squareup.wire.Message<InnerInfo, InnerInfo.Builder> {
          public static final ProtoAdapter<InnerInfo> ADAPTER = new ProtoAdapter_InnerInfo();

          private static final long serialVersionUID = 0L;

          @WireField(
              tag = 1,
              adapter = "com.squareup.wire.ProtoAdapter#INT64",
              label = WireField.Label.OMIT_IDENTITY
          )
          public final long value;

          public InnerInfo(long value) {
            this(value, ByteString.EMPTY);
          }

          public InnerInfo(long value, ByteString unknownFields) {
            super(ADAPTER, unknownFields);
            this.value = value;
          }

          @Override
          public Builder newBuilder() {
            Builder builder = new Builder();
            builder.value = value;
            builder.addUnknownFields(unknownFields());
            return builder;
          }

          @Override
          public boolean equals(Object other) {
            if (other == this) return true;
            if (!(other instanceof InnerInfo)) return false;
            InnerInfo o = (InnerInfo) other;
            return unknownFields().equals(o.unknownFields())
                && Internal.equals(value, o.value);
          }

          @Override
          public int hashCode() {
            int result = super.hashCode;
            if (result == 0) {
              result = unknownFields().hashCode();
              result = result * 37 + Long.hashCode(value);
              super.hashCode = result;
            }
            return result;
          }

          @Override
          public String toString() {
            StringBuilder builder = new StringBuilder();
            builder.append(", value=").append(value);
            return builder.replace(0, 2, "InnerInfo{").append('}').toString();
          }

          public static final class Builder extends com.squareup.wire.Message.Builder<InnerInfo, Builder> {
            public long value;

            public Builder() {
              value = 0L;
            }

            public Builder value(long value) {
              this.value = value;
              return this;
            }

            @Override
            public InnerInfo build() {
              return new InnerInfo(value, super.buildUnknownFields());
            }
          }

          private static final class ProtoAdapter_InnerInfo extends ProtoAdapter<InnerInfo> {
            public ProtoAdapter_InnerInfo() {
              super(FieldEncoding.LENGTH_DELIMITED, InnerInfo.class, "type.googleapis.com/niconicobulletcomments.BulletComment.MessageItem.Meta.AdditionalInfo.InnerInfo", Syntax.PROTO_3, null, "NicoNicoBulletComments.proto");
            }

            @Override
            public int encodedSize(InnerInfo value) {
              int result = 0;
              if (!Objects.equals(value.value, 0L)) {
                result += ProtoAdapter.INT64.encodedSizeWithTag(1, value.value);
              }
              result += value.unknownFields().size();
              return result;
            }

            @Override
            public void encode(ProtoWriter writer, InnerInfo value) throws IOException {
              if (!Objects.equals(value.value, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 1, value.value);
              writer.writeBytes(value.unknownFields());
            }

            @Override
            public void encode(ReverseProtoWriter writer, InnerInfo value) throws IOException {
              writer.writeBytes(value.unknownFields());
              if (!Objects.equals(value.value, 0L)) ProtoAdapter.INT64.encodeWithTag(writer, 1, value.value);
            }

            @Override
            public InnerInfo decode(ProtoReader reader) throws IOException {
              Builder builder = new Builder();
              long token = reader.beginMessage();
              for (int tag; (tag = reader.nextTag()) != -1;) {
                switch (tag) {
                  case 1: builder.value(ProtoAdapter.INT64.decode(reader)); break;
                  default: {
                    reader.readUnknownField(tag);
                  }
                }
              }
              builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
              return builder.build();
            }

            @Override
            public InnerInfo redact(InnerInfo value) {
              Builder builder = value.newBuilder();
              builder.clearUnknownFields();
              return builder.build();
            }
          }
        }

        private static final class ProtoAdapter_AdditionalInfo extends ProtoAdapter<AdditionalInfo> {
          public ProtoAdapter_AdditionalInfo() {
            super(FieldEncoding.LENGTH_DELIMITED, AdditionalInfo.class, "type.googleapis.com/niconicobulletcomments.BulletComment.MessageItem.Meta.AdditionalInfo", Syntax.PROTO_3, null, "NicoNicoBulletComments.proto");
          }

          @Override
          public int encodedSize(AdditionalInfo value) {
            int result = 0;
            if (!Objects.equals(value.inner_info, null)) {
              result += InnerInfo.ADAPTER.encodedSizeWithTag(1, value.inner_info);
            }
            result += value.unknownFields().size();
            return result;
          }

          @Override
          public void encode(ProtoWriter writer, AdditionalInfo value) throws IOException {
            if (!Objects.equals(value.inner_info, null)) InnerInfo.ADAPTER.encodeWithTag(writer, 1, value.inner_info);
            writer.writeBytes(value.unknownFields());
          }

          @Override
          public void encode(ReverseProtoWriter writer, AdditionalInfo value) throws IOException {
            writer.writeBytes(value.unknownFields());
            if (!Objects.equals(value.inner_info, null)) InnerInfo.ADAPTER.encodeWithTag(writer, 1, value.inner_info);
          }

          @Override
          public AdditionalInfo decode(ProtoReader reader) throws IOException {
            Builder builder = new Builder();
            long token = reader.beginMessage();
            for (int tag; (tag = reader.nextTag()) != -1;) {
              switch (tag) {
                case 1: builder.inner_info(InnerInfo.ADAPTER.decode(reader)); break;
                default: {
                  reader.readUnknownField(tag);
                }
              }
            }
            builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
            return builder.build();
          }

          @Override
          public AdditionalInfo redact(AdditionalInfo value) {
            Builder builder = value.newBuilder();
            if (builder.inner_info != null) builder.inner_info = InnerInfo.ADAPTER.redact(builder.inner_info);
            builder.clearUnknownFields();
            return builder.build();
          }
        }
      }

      private static final class ProtoAdapter_Meta extends ProtoAdapter<Meta> {
        public ProtoAdapter_Meta() {
          super(FieldEncoding.LENGTH_DELIMITED, Meta.class, "type.googleapis.com/niconicobulletcomments.BulletComment.MessageItem.Meta", Syntax.PROTO_3, null, "NicoNicoBulletComments.proto");
        }

        @Override
        public int encodedSize(Meta value) {
          int result = 0;
          if (!Objects.equals(value.id, "")) {
            result += ProtoAdapter.STRING.encodedSizeWithTag(1, value.id);
          }
          if (!Objects.equals(value.timestamp, null)) {
            result += Timestamp.ADAPTER.encodedSizeWithTag(2, value.timestamp);
          }
          if (!Objects.equals(value.additional_info, null)) {
            result += AdditionalInfo.ADAPTER.encodedSizeWithTag(3, value.additional_info);
          }
          result += value.unknownFields().size();
          return result;
        }

        @Override
        public void encode(ProtoWriter writer, Meta value) throws IOException {
          if (!Objects.equals(value.id, "")) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id);
          if (!Objects.equals(value.timestamp, null)) Timestamp.ADAPTER.encodeWithTag(writer, 2, value.timestamp);
          if (!Objects.equals(value.additional_info, null)) AdditionalInfo.ADAPTER.encodeWithTag(writer, 3, value.additional_info);
          writer.writeBytes(value.unknownFields());
        }

        @Override
        public void encode(ReverseProtoWriter writer, Meta value) throws IOException {
          writer.writeBytes(value.unknownFields());
          if (!Objects.equals(value.additional_info, null)) AdditionalInfo.ADAPTER.encodeWithTag(writer, 3, value.additional_info);
          if (!Objects.equals(value.timestamp, null)) Timestamp.ADAPTER.encodeWithTag(writer, 2, value.timestamp);
          if (!Objects.equals(value.id, "")) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id);
        }

        @Override
        public Meta decode(ProtoReader reader) throws IOException {
          Builder builder = new Builder();
          long token = reader.beginMessage();
          for (int tag; (tag = reader.nextTag()) != -1;) {
            switch (tag) {
              case 1: builder.id(ProtoAdapter.STRING.decode(reader)); break;
              case 2: builder.timestamp(Timestamp.ADAPTER.decode(reader)); break;
              case 3: builder.additional_info(AdditionalInfo.ADAPTER.decode(reader)); break;
              default: {
                reader.readUnknownField(tag);
              }
            }
          }
          builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
          return builder.build();
        }

        @Override
        public Meta redact(Meta value) {
          Builder builder = value.newBuilder();
          if (builder.timestamp != null) builder.timestamp = Timestamp.ADAPTER.redact(builder.timestamp);
          if (builder.additional_info != null) builder.additional_info = AdditionalInfo.ADAPTER.redact(builder.additional_info);
          builder.clearUnknownFields();
          return builder.build();
        }
      }
    }

    public static final class Message extends com.squareup.wire.Message<Message, Message.Builder> {
      public static final ProtoAdapter<Message> ADAPTER = new ProtoAdapter_Message();

      private static final long serialVersionUID = 0L;

      @WireField(
          tag = 1,
          adapter = "org.schabi.newpipe.extractor.services.niconico.protobuf.BulletComment$MessageItem$Message$InnerMessage#ADAPTER",
          label = WireField.Label.OMIT_IDENTITY,
          jsonName = "textMessage"
      )
      public final InnerMessage text_message;

      @WireField(
          tag = 8,
          adapter = "org.schabi.newpipe.extractor.services.niconico.protobuf.BulletComment$MessageItem$Message$InnerMessage#ADAPTER",
          label = WireField.Label.OMIT_IDENTITY
      )
      public final InnerMessage gift;

      public Message(InnerMessage text_message, InnerMessage gift) {
        this(text_message, gift, ByteString.EMPTY);
      }

      public Message(InnerMessage text_message, InnerMessage gift, ByteString unknownFields) {
        super(ADAPTER, unknownFields);
        this.text_message = text_message;
        this.gift = gift;
      }

      @Override
      public Builder newBuilder() {
        Builder builder = new Builder();
        builder.text_message = text_message;
        builder.gift = gift;
        builder.addUnknownFields(unknownFields());
        return builder;
      }

      @Override
      public boolean equals(Object other) {
        if (other == this) return true;
        if (!(other instanceof Message)) return false;
        Message o = (Message) other;
        return unknownFields().equals(o.unknownFields())
            && Internal.equals(text_message, o.text_message)
            && Internal.equals(gift, o.gift);
      }

      @Override
      public int hashCode() {
        int result = super.hashCode;
        if (result == 0) {
          result = unknownFields().hashCode();
          result = result * 37 + (text_message != null ? text_message.hashCode() : 0);
          result = result * 37 + (gift != null ? gift.hashCode() : 0);
          super.hashCode = result;
        }
        return result;
      }

      @Override
      public String toString() {
        StringBuilder builder = new StringBuilder();
        if (text_message != null) builder.append(", text_message=").append(text_message);
        if (gift != null) builder.append(", gift=").append(gift);
        return builder.replace(0, 2, "Message{").append('}').toString();
      }

      public static final class Builder extends com.squareup.wire.Message.Builder<Message, Builder> {
        public InnerMessage text_message;

        public InnerMessage gift;

        public Builder() {
        }

        public Builder text_message(InnerMessage text_message) {
          this.text_message = text_message;
          return this;
        }

        public Builder gift(InnerMessage gift) {
          this.gift = gift;
          return this;
        }

        @Override
        public Message build() {
          return new Message(text_message, gift, super.buildUnknownFields());
        }
      }

      public static final class InnerMessage extends com.squareup.wire.Message<InnerMessage, InnerMessage.Builder> {
        public static final ProtoAdapter<InnerMessage> ADAPTER = new ProtoAdapter_InnerMessage();

        private static final long serialVersionUID = 0L;

        @WireField(
            tag = 1,
            adapter = "com.squareup.wire.ProtoAdapter#STRING",
            label = WireField.Label.OMIT_IDENTITY
        )
        public final String text;

        @WireField(
            tag = 2,
            adapter = "com.squareup.wire.ProtoAdapter#STRING",
            label = WireField.Label.OMIT_IDENTITY
        )
        public final String username;

        @WireField(
            tag = 3,
            adapter = "com.squareup.wire.ProtoAdapter#INT32",
            label = WireField.Label.OMIT_IDENTITY,
            jsonName = "timeToNow"
        )
        public final int time_to_now;

        @WireField(
            tag = 4,
            adapter = "com.squareup.wire.ProtoAdapter#INT32",
            label = WireField.Label.OMIT_IDENTITY,
            jsonName = "bulletCommentLocation"
        )
        public final int bullet_comment_location;

        @WireField(
            tag = 5,
            adapter = "com.squareup.wire.ProtoAdapter#INT32",
            label = WireField.Label.OMIT_IDENTITY
        )
        public final int userid;

        @WireField(
            tag = 6,
            adapter = "com.squareup.wire.ProtoAdapter#STRING",
            label = WireField.Label.OMIT_IDENTITY
        )
        public final String identifier;

        @WireField(
            tag = 7,
            adapter = "com.squareup.wire.ProtoAdapter#BYTES",
            label = WireField.Label.OMIT_IDENTITY,
            jsonName = "unknownBytes2"
        )
        public final ByteString unknown_bytes_2;

        @WireField(
            tag = 8,
            adapter = "com.squareup.wire.ProtoAdapter#INT32",
            label = WireField.Label.OMIT_IDENTITY
        )
        public final int id;

        public InnerMessage(String text, String username, int time_to_now,
            int bullet_comment_location, int userid, String identifier, ByteString unknown_bytes_2,
            int id) {
          this(text, username, time_to_now, bullet_comment_location, userid, identifier, unknown_bytes_2, id, ByteString.EMPTY);
        }

        public InnerMessage(String text, String username, int time_to_now,
            int bullet_comment_location, int userid, String identifier, ByteString unknown_bytes_2,
            int id, ByteString unknownFields) {
          super(ADAPTER, unknownFields);
          if (text == null) {
            throw new IllegalArgumentException("text == null");
          }
          this.text = text;
          if (username == null) {
            throw new IllegalArgumentException("username == null");
          }
          this.username = username;
          this.time_to_now = time_to_now;
          this.bullet_comment_location = bullet_comment_location;
          this.userid = userid;
          if (identifier == null) {
            throw new IllegalArgumentException("identifier == null");
          }
          this.identifier = identifier;
          if (unknown_bytes_2 == null) {
            throw new IllegalArgumentException("unknown_bytes_2 == null");
          }
          this.unknown_bytes_2 = unknown_bytes_2;
          this.id = id;
        }

        @Override
        public Builder newBuilder() {
          Builder builder = new Builder();
          builder.text = text;
          builder.username = username;
          builder.time_to_now = time_to_now;
          builder.bullet_comment_location = bullet_comment_location;
          builder.userid = userid;
          builder.identifier = identifier;
          builder.unknown_bytes_2 = unknown_bytes_2;
          builder.id = id;
          builder.addUnknownFields(unknownFields());
          return builder;
        }

        @Override
        public boolean equals(Object other) {
          if (other == this) return true;
          if (!(other instanceof InnerMessage)) return false;
          InnerMessage o = (InnerMessage) other;
          return unknownFields().equals(o.unknownFields())
              && Internal.equals(text, o.text)
              && Internal.equals(username, o.username)
              && Internal.equals(time_to_now, o.time_to_now)
              && Internal.equals(bullet_comment_location, o.bullet_comment_location)
              && Internal.equals(userid, o.userid)
              && Internal.equals(identifier, o.identifier)
              && Internal.equals(unknown_bytes_2, o.unknown_bytes_2)
              && Internal.equals(id, o.id);
        }

        @Override
        public int hashCode() {
          int result = super.hashCode;
          if (result == 0) {
            result = unknownFields().hashCode();
            result = result * 37 + (text != null ? text.hashCode() : 0);
            result = result * 37 + (username != null ? username.hashCode() : 0);
            result = result * 37 + Integer.hashCode(time_to_now);
            result = result * 37 + Integer.hashCode(bullet_comment_location);
            result = result * 37 + Integer.hashCode(userid);
            result = result * 37 + (identifier != null ? identifier.hashCode() : 0);
            result = result * 37 + (unknown_bytes_2 != null ? unknown_bytes_2.hashCode() : 0);
            result = result * 37 + Integer.hashCode(id);
            super.hashCode = result;
          }
          return result;
        }

        @Override
        public String toString() {
          StringBuilder builder = new StringBuilder();
          if (text != null) builder.append(", text=").append(Internal.sanitize(text));
          if (username != null) builder.append(", username=").append(Internal.sanitize(username));
          builder.append(", time_to_now=").append(time_to_now);
          builder.append(", bullet_comment_location=").append(bullet_comment_location);
          builder.append(", userid=").append(userid);
          if (identifier != null) builder.append(", identifier=").append(Internal.sanitize(identifier));
          if (unknown_bytes_2 != null) builder.append(", unknown_bytes_2=").append(unknown_bytes_2);
          builder.append(", id=").append(id);
          return builder.replace(0, 2, "InnerMessage{").append('}').toString();
        }

        public static final class Builder extends com.squareup.wire.Message.Builder<InnerMessage, Builder> {
          public String text;

          public String username;

          public int time_to_now;

          public int bullet_comment_location;

          public int userid;

          public String identifier;

          public ByteString unknown_bytes_2;

          public int id;

          public Builder() {
            text = "";
            username = "";
            time_to_now = 0;
            bullet_comment_location = 0;
            userid = 0;
            identifier = "";
            unknown_bytes_2 = ByteString.EMPTY;
            id = 0;
          }

          public Builder text(String text) {
            this.text = text;
            return this;
          }

          public Builder username(String username) {
            this.username = username;
            return this;
          }

          public Builder time_to_now(int time_to_now) {
            this.time_to_now = time_to_now;
            return this;
          }

          public Builder bullet_comment_location(int bullet_comment_location) {
            this.bullet_comment_location = bullet_comment_location;
            return this;
          }

          public Builder userid(int userid) {
            this.userid = userid;
            return this;
          }

          public Builder identifier(String identifier) {
            this.identifier = identifier;
            return this;
          }

          public Builder unknown_bytes_2(ByteString unknown_bytes_2) {
            this.unknown_bytes_2 = unknown_bytes_2;
            return this;
          }

          public Builder id(int id) {
            this.id = id;
            return this;
          }

          @Override
          public InnerMessage build() {
            return new InnerMessage(text, username, time_to_now, bullet_comment_location, userid, identifier, unknown_bytes_2, id, super.buildUnknownFields());
          }
        }

        private static final class ProtoAdapter_InnerMessage extends ProtoAdapter<InnerMessage> {
          public ProtoAdapter_InnerMessage() {
            super(FieldEncoding.LENGTH_DELIMITED, InnerMessage.class, "type.googleapis.com/niconicobulletcomments.BulletComment.MessageItem.Message.InnerMessage", Syntax.PROTO_3, null, "NicoNicoBulletComments.proto");
          }

          @Override
          public int encodedSize(InnerMessage value) {
            int result = 0;
            if (!Objects.equals(value.text, "")) {
              result += ProtoAdapter.STRING.encodedSizeWithTag(1, value.text);
            }
            if (!Objects.equals(value.username, "")) {
              result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.username);
            }
            if (!Objects.equals(value.time_to_now, 0)) {
              result += ProtoAdapter.INT32.encodedSizeWithTag(3, value.time_to_now);
            }
            if (!Objects.equals(value.bullet_comment_location, 0)) {
              result += ProtoAdapter.INT32.encodedSizeWithTag(4, value.bullet_comment_location);
            }
            if (!Objects.equals(value.userid, 0)) {
              result += ProtoAdapter.INT32.encodedSizeWithTag(5, value.userid);
            }
            if (!Objects.equals(value.identifier, "")) {
              result += ProtoAdapter.STRING.encodedSizeWithTag(6, value.identifier);
            }
            if (!Objects.equals(value.unknown_bytes_2, ByteString.EMPTY)) {
              result += ProtoAdapter.BYTES.encodedSizeWithTag(7, value.unknown_bytes_2);
            }
            if (!Objects.equals(value.id, 0)) {
              result += ProtoAdapter.INT32.encodedSizeWithTag(8, value.id);
            }
            result += value.unknownFields().size();
            return result;
          }

          @Override
          public void encode(ProtoWriter writer, InnerMessage value) throws IOException {
            if (!Objects.equals(value.text, "")) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.text);
            if (!Objects.equals(value.username, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.username);
            if (!Objects.equals(value.time_to_now, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 3, value.time_to_now);
            if (!Objects.equals(value.bullet_comment_location, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 4, value.bullet_comment_location);
            if (!Objects.equals(value.userid, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 5, value.userid);
            if (!Objects.equals(value.identifier, "")) ProtoAdapter.STRING.encodeWithTag(writer, 6, value.identifier);
            if (!Objects.equals(value.unknown_bytes_2, ByteString.EMPTY)) ProtoAdapter.BYTES.encodeWithTag(writer, 7, value.unknown_bytes_2);
            if (!Objects.equals(value.id, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 8, value.id);
            writer.writeBytes(value.unknownFields());
          }

          @Override
          public void encode(ReverseProtoWriter writer, InnerMessage value) throws IOException {
            writer.writeBytes(value.unknownFields());
            if (!Objects.equals(value.id, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 8, value.id);
            if (!Objects.equals(value.unknown_bytes_2, ByteString.EMPTY)) ProtoAdapter.BYTES.encodeWithTag(writer, 7, value.unknown_bytes_2);
            if (!Objects.equals(value.identifier, "")) ProtoAdapter.STRING.encodeWithTag(writer, 6, value.identifier);
            if (!Objects.equals(value.userid, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 5, value.userid);
            if (!Objects.equals(value.bullet_comment_location, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 4, value.bullet_comment_location);
            if (!Objects.equals(value.time_to_now, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 3, value.time_to_now);
            if (!Objects.equals(value.username, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.username);
            if (!Objects.equals(value.text, "")) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.text);
          }

          @Override
          public InnerMessage decode(ProtoReader reader) throws IOException {
            Builder builder = new Builder();
            long token = reader.beginMessage();
            for (int tag; (tag = reader.nextTag()) != -1;) {
              switch (tag) {
                case 1: builder.text(ProtoAdapter.STRING.decode(reader)); break;
                case 2: builder.username(ProtoAdapter.STRING.decode(reader)); break;
                case 3: builder.time_to_now(ProtoAdapter.INT32.decode(reader)); break;
                case 4: builder.bullet_comment_location(ProtoAdapter.INT32.decode(reader)); break;
                case 5: builder.userid(ProtoAdapter.INT32.decode(reader)); break;
                case 6: builder.identifier(ProtoAdapter.STRING.decode(reader)); break;
                case 7: builder.unknown_bytes_2(ProtoAdapter.BYTES.decode(reader)); break;
                case 8: builder.id(ProtoAdapter.INT32.decode(reader)); break;
                default: {
                  reader.readUnknownField(tag);
                }
              }
            }
            builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
            return builder.build();
          }

          @Override
          public InnerMessage redact(InnerMessage value) {
            Builder builder = value.newBuilder();
            builder.clearUnknownFields();
            return builder.build();
          }
        }
      }

      public static final class Gift extends com.squareup.wire.Message<Gift, Gift.Builder> {
        public static final ProtoAdapter<Gift> ADAPTER = new ProtoAdapter_Gift();

        private static final long serialVersionUID = 0L;

        @WireField(
            tag = 1,
            adapter = "com.squareup.wire.ProtoAdapter#STRING",
            label = WireField.Label.OMIT_IDENTITY,
            jsonName = "giftName"
        )
        public final String gift_name;

        @WireField(
            tag = 2,
            adapter = "com.squareup.wire.ProtoAdapter#STRING",
            label = WireField.Label.OMIT_IDENTITY
        )
        public final String userid;

        @WireField(
            tag = 3,
            adapter = "com.squareup.wire.ProtoAdapter#STRING",
            label = WireField.Label.OMIT_IDENTITY
        )
        public final String username;

        @WireField(
            tag = 4,
            adapter = "com.squareup.wire.ProtoAdapter#INT32",
            label = WireField.Label.OMIT_IDENTITY
        )
        public final int count;

        @WireField(
            tag = 5,
            adapter = "com.squareup.wire.ProtoAdapter#STRING",
            label = WireField.Label.OMIT_IDENTITY,
            jsonName = "giftText"
        )
        public final String gift_text;

        @WireField(
            tag = 6,
            adapter = "com.squareup.wire.ProtoAdapter#INT32",
            label = WireField.Label.OMIT_IDENTITY
        )
        public final int id;

        public Gift(String gift_name, String userid, String username, int count, String gift_text,
            int id) {
          this(gift_name, userid, username, count, gift_text, id, ByteString.EMPTY);
        }

        public Gift(String gift_name, String userid, String username, int count, String gift_text,
            int id, ByteString unknownFields) {
          super(ADAPTER, unknownFields);
          if (gift_name == null) {
            throw new IllegalArgumentException("gift_name == null");
          }
          this.gift_name = gift_name;
          if (userid == null) {
            throw new IllegalArgumentException("userid == null");
          }
          this.userid = userid;
          if (username == null) {
            throw new IllegalArgumentException("username == null");
          }
          this.username = username;
          this.count = count;
          if (gift_text == null) {
            throw new IllegalArgumentException("gift_text == null");
          }
          this.gift_text = gift_text;
          this.id = id;
        }

        @Override
        public Builder newBuilder() {
          Builder builder = new Builder();
          builder.gift_name = gift_name;
          builder.userid = userid;
          builder.username = username;
          builder.count = count;
          builder.gift_text = gift_text;
          builder.id = id;
          builder.addUnknownFields(unknownFields());
          return builder;
        }

        @Override
        public boolean equals(Object other) {
          if (other == this) return true;
          if (!(other instanceof Gift)) return false;
          Gift o = (Gift) other;
          return unknownFields().equals(o.unknownFields())
              && Internal.equals(gift_name, o.gift_name)
              && Internal.equals(userid, o.userid)
              && Internal.equals(username, o.username)
              && Internal.equals(count, o.count)
              && Internal.equals(gift_text, o.gift_text)
              && Internal.equals(id, o.id);
        }

        @Override
        public int hashCode() {
          int result = super.hashCode;
          if (result == 0) {
            result = unknownFields().hashCode();
            result = result * 37 + (gift_name != null ? gift_name.hashCode() : 0);
            result = result * 37 + (userid != null ? userid.hashCode() : 0);
            result = result * 37 + (username != null ? username.hashCode() : 0);
            result = result * 37 + Integer.hashCode(count);
            result = result * 37 + (gift_text != null ? gift_text.hashCode() : 0);
            result = result * 37 + Integer.hashCode(id);
            super.hashCode = result;
          }
          return result;
        }

        @Override
        public String toString() {
          StringBuilder builder = new StringBuilder();
          if (gift_name != null) builder.append(", gift_name=").append(Internal.sanitize(gift_name));
          if (userid != null) builder.append(", userid=").append(Internal.sanitize(userid));
          if (username != null) builder.append(", username=").append(Internal.sanitize(username));
          builder.append(", count=").append(count);
          if (gift_text != null) builder.append(", gift_text=").append(Internal.sanitize(gift_text));
          builder.append(", id=").append(id);
          return builder.replace(0, 2, "Gift{").append('}').toString();
        }

        public static final class Builder extends com.squareup.wire.Message.Builder<Gift, Builder> {
          public String gift_name;

          public String userid;

          public String username;

          public int count;

          public String gift_text;

          public int id;

          public Builder() {
            gift_name = "";
            userid = "";
            username = "";
            count = 0;
            gift_text = "";
            id = 0;
          }

          public Builder gift_name(String gift_name) {
            this.gift_name = gift_name;
            return this;
          }

          public Builder userid(String userid) {
            this.userid = userid;
            return this;
          }

          public Builder username(String username) {
            this.username = username;
            return this;
          }

          public Builder count(int count) {
            this.count = count;
            return this;
          }

          public Builder gift_text(String gift_text) {
            this.gift_text = gift_text;
            return this;
          }

          public Builder id(int id) {
            this.id = id;
            return this;
          }

          @Override
          public Gift build() {
            return new Gift(gift_name, userid, username, count, gift_text, id, super.buildUnknownFields());
          }
        }

        private static final class ProtoAdapter_Gift extends ProtoAdapter<Gift> {
          public ProtoAdapter_Gift() {
            super(FieldEncoding.LENGTH_DELIMITED, Gift.class, "type.googleapis.com/niconicobulletcomments.BulletComment.MessageItem.Message.Gift", Syntax.PROTO_3, null, "NicoNicoBulletComments.proto");
          }

          @Override
          public int encodedSize(Gift value) {
            int result = 0;
            if (!Objects.equals(value.gift_name, "")) {
              result += ProtoAdapter.STRING.encodedSizeWithTag(1, value.gift_name);
            }
            if (!Objects.equals(value.userid, "")) {
              result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.userid);
            }
            if (!Objects.equals(value.username, "")) {
              result += ProtoAdapter.STRING.encodedSizeWithTag(3, value.username);
            }
            if (!Objects.equals(value.count, 0)) {
              result += ProtoAdapter.INT32.encodedSizeWithTag(4, value.count);
            }
            if (!Objects.equals(value.gift_text, "")) {
              result += ProtoAdapter.STRING.encodedSizeWithTag(5, value.gift_text);
            }
            if (!Objects.equals(value.id, 0)) {
              result += ProtoAdapter.INT32.encodedSizeWithTag(6, value.id);
            }
            result += value.unknownFields().size();
            return result;
          }

          @Override
          public void encode(ProtoWriter writer, Gift value) throws IOException {
            if (!Objects.equals(value.gift_name, "")) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.gift_name);
            if (!Objects.equals(value.userid, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.userid);
            if (!Objects.equals(value.username, "")) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.username);
            if (!Objects.equals(value.count, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 4, value.count);
            if (!Objects.equals(value.gift_text, "")) ProtoAdapter.STRING.encodeWithTag(writer, 5, value.gift_text);
            if (!Objects.equals(value.id, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 6, value.id);
            writer.writeBytes(value.unknownFields());
          }

          @Override
          public void encode(ReverseProtoWriter writer, Gift value) throws IOException {
            writer.writeBytes(value.unknownFields());
            if (!Objects.equals(value.id, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 6, value.id);
            if (!Objects.equals(value.gift_text, "")) ProtoAdapter.STRING.encodeWithTag(writer, 5, value.gift_text);
            if (!Objects.equals(value.count, 0)) ProtoAdapter.INT32.encodeWithTag(writer, 4, value.count);
            if (!Objects.equals(value.username, "")) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.username);
            if (!Objects.equals(value.userid, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.userid);
            if (!Objects.equals(value.gift_name, "")) ProtoAdapter.STRING.encodeWithTag(writer, 1, value.gift_name);
          }

          @Override
          public Gift decode(ProtoReader reader) throws IOException {
            Builder builder = new Builder();
            long token = reader.beginMessage();
            for (int tag; (tag = reader.nextTag()) != -1;) {
              switch (tag) {
                case 1: builder.gift_name(ProtoAdapter.STRING.decode(reader)); break;
                case 2: builder.userid(ProtoAdapter.STRING.decode(reader)); break;
                case 3: builder.username(ProtoAdapter.STRING.decode(reader)); break;
                case 4: builder.count(ProtoAdapter.INT32.decode(reader)); break;
                case 5: builder.gift_text(ProtoAdapter.STRING.decode(reader)); break;
                case 6: builder.id(ProtoAdapter.INT32.decode(reader)); break;
                default: {
                  reader.readUnknownField(tag);
                }
              }
            }
            builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
            return builder.build();
          }

          @Override
          public Gift redact(Gift value) {
            Builder builder = value.newBuilder();
            builder.clearUnknownFields();
            return builder.build();
          }
        }
      }

      private static final class ProtoAdapter_Message extends ProtoAdapter<Message> {
        public ProtoAdapter_Message() {
          super(FieldEncoding.LENGTH_DELIMITED, Message.class, "type.googleapis.com/niconicobulletcomments.BulletComment.MessageItem.Message", Syntax.PROTO_3, null, "NicoNicoBulletComments.proto");
        }

        @Override
        public int encodedSize(Message value) {
          int result = 0;
          if (!Objects.equals(value.text_message, null)) {
            result += InnerMessage.ADAPTER.encodedSizeWithTag(1, value.text_message);
          }
          if (!Objects.equals(value.gift, null)) {
            result += InnerMessage.ADAPTER.encodedSizeWithTag(8, value.gift);
          }
          result += value.unknownFields().size();
          return result;
        }

        @Override
        public void encode(ProtoWriter writer, Message value) throws IOException {
          if (!Objects.equals(value.text_message, null)) InnerMessage.ADAPTER.encodeWithTag(writer, 1, value.text_message);
          if (!Objects.equals(value.gift, null)) InnerMessage.ADAPTER.encodeWithTag(writer, 8, value.gift);
          writer.writeBytes(value.unknownFields());
        }

        @Override
        public void encode(ReverseProtoWriter writer, Message value) throws IOException {
          writer.writeBytes(value.unknownFields());
          if (!Objects.equals(value.gift, null)) InnerMessage.ADAPTER.encodeWithTag(writer, 8, value.gift);
          if (!Objects.equals(value.text_message, null)) InnerMessage.ADAPTER.encodeWithTag(writer, 1, value.text_message);
        }

        @Override
        public Message decode(ProtoReader reader) throws IOException {
          Builder builder = new Builder();
          long token = reader.beginMessage();
          for (int tag; (tag = reader.nextTag()) != -1;) {
            switch (tag) {
              case 1: builder.text_message(InnerMessage.ADAPTER.decode(reader)); break;
              case 8: builder.gift(InnerMessage.ADAPTER.decode(reader)); break;
              default: {
                reader.readUnknownField(tag);
              }
            }
          }
          builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
          return builder.build();
        }

        @Override
        public Message redact(Message value) {
          Builder builder = value.newBuilder();
          if (builder.text_message != null) builder.text_message = InnerMessage.ADAPTER.redact(builder.text_message);
          if (builder.gift != null) builder.gift = InnerMessage.ADAPTER.redact(builder.gift);
          builder.clearUnknownFields();
          return builder.build();
        }
      }
    }

    private static final class ProtoAdapter_MessageItem extends ProtoAdapter<MessageItem> {
      public ProtoAdapter_MessageItem() {
        super(FieldEncoding.LENGTH_DELIMITED, MessageItem.class, "type.googleapis.com/niconicobulletcomments.BulletComment.MessageItem", Syntax.PROTO_3, null, "NicoNicoBulletComments.proto");
      }

      @Override
      public int encodedSize(MessageItem value) {
        int result = 0;
        if (!Objects.equals(value.meta, null)) {
          result += Meta.ADAPTER.encodedSizeWithTag(1, value.meta);
        }
        if (!Objects.equals(value.message, null)) {
          result += Message.ADAPTER.encodedSizeWithTag(2, value.message);
        }
        result += value.unknownFields().size();
        return result;
      }

      @Override
      public void encode(ProtoWriter writer, MessageItem value) throws IOException {
        if (!Objects.equals(value.meta, null)) Meta.ADAPTER.encodeWithTag(writer, 1, value.meta);
        if (!Objects.equals(value.message, null)) Message.ADAPTER.encodeWithTag(writer, 2, value.message);
        writer.writeBytes(value.unknownFields());
      }

      @Override
      public void encode(ReverseProtoWriter writer, MessageItem value) throws IOException {
        writer.writeBytes(value.unknownFields());
        if (!Objects.equals(value.message, null)) Message.ADAPTER.encodeWithTag(writer, 2, value.message);
        if (!Objects.equals(value.meta, null)) Meta.ADAPTER.encodeWithTag(writer, 1, value.meta);
      }

      @Override
      public MessageItem decode(ProtoReader reader) throws IOException {
        Builder builder = new Builder();
        long token = reader.beginMessage();
        for (int tag; (tag = reader.nextTag()) != -1;) {
          switch (tag) {
            case 1: builder.meta(Meta.ADAPTER.decode(reader)); break;
            case 2: builder.message(Message.ADAPTER.decode(reader)); break;
            default: {
              reader.readUnknownField(tag);
            }
          }
        }
        builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
        return builder.build();
      }

      @Override
      public MessageItem redact(MessageItem value) {
        Builder builder = value.newBuilder();
        if (builder.meta != null) builder.meta = Meta.ADAPTER.redact(builder.meta);
        if (builder.message != null) builder.message = Message.ADAPTER.redact(builder.message);
        builder.clearUnknownFields();
        return builder.build();
      }
    }
  }

  private static final class ProtoAdapter_BulletComment extends ProtoAdapter<BulletComment> {
    public ProtoAdapter_BulletComment() {
      super(FieldEncoding.LENGTH_DELIMITED, BulletComment.class, "type.googleapis.com/niconicobulletcomments.BulletComment", Syntax.PROTO_3, null, "NicoNicoBulletComments.proto");
    }

    @Override
    public int encodedSize(BulletComment value) {
      int result = 0;
      result += MessageItem.ADAPTER.asRepeated().encodedSizeWithTag(1, value.items);
      if (!Objects.equals(value.backward_url, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(2, value.backward_url);
      }
      if (!Objects.equals(value.snapshot_url, "")) {
        result += ProtoAdapter.STRING.encodedSizeWithTag(3, value.snapshot_url);
      }
      result += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(4, value.segments);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, BulletComment value) throws IOException {
      MessageItem.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.items);
      if (!Objects.equals(value.backward_url, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.backward_url);
      if (!Objects.equals(value.snapshot_url, "")) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.snapshot_url);
      ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 4, value.segments);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public void encode(ReverseProtoWriter writer, BulletComment value) throws IOException {
      writer.writeBytes(value.unknownFields());
      ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 4, value.segments);
      if (!Objects.equals(value.snapshot_url, "")) ProtoAdapter.STRING.encodeWithTag(writer, 3, value.snapshot_url);
      if (!Objects.equals(value.backward_url, "")) ProtoAdapter.STRING.encodeWithTag(writer, 2, value.backward_url);
      MessageItem.ADAPTER.asRepeated().encodeWithTag(writer, 1, value.items);
    }

    @Override
    public BulletComment decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.items.add(MessageItem.ADAPTER.decode(reader)); break;
          case 2: builder.backward_url(ProtoAdapter.STRING.decode(reader)); break;
          case 3: builder.snapshot_url(ProtoAdapter.STRING.decode(reader)); break;
          case 4: builder.segments.add(ProtoAdapter.STRING.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public BulletComment redact(BulletComment value) {
      Builder builder = value.newBuilder();
      Internal.redactElements(builder.items, MessageItem.ADAPTER);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
