// Code generated by Wire protocol buffer compiler, do not edit.
// Source: youtubesearchfilter.DateFilter in youtubeFilters.proto
package org.schabi.newpipe.extractor.services.youtube.search.filter.protobuf;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum DateFilter implements WireEnum {
  hour(1),

  day(2),

  week(3),

  month(4),

  year(5);

  public static final ProtoAdapter<DateFilter> ADAPTER = new ProtoAdapter_DateFilter();

  private final int value;

  DateFilter(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static DateFilter fromValue(int value) {
    switch (value) {
      case 1: return hour;
      case 2: return day;
      case 3: return week;
      case 4: return month;
      case 5: return year;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_DateFilter extends EnumAdapter<DateFilter> {
    ProtoAdapter_DateFilter() {
      super(DateFilter.class, Syntax.PROTO_2, null);
    }

    @Override
    protected DateFilter fromValue(int value) {
      return DateFilter.fromValue(value);
    }
  }
}
