// Code generated by Wire protocol buffer compiler, do not edit.
// Source: youtubesearchfilter.ExtraFeatures in youtubeFilters.proto
package org.schabi.newpipe.extractor.services.youtube.search.filter.protobuf;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum ExtraFeatures implements WireEnum {
  verbatim(0);

  public static final ProtoAdapter<ExtraFeatures> ADAPTER = new ProtoAdapter_ExtraFeatures();

  private final int value;

  ExtraFeatures(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static ExtraFeatures fromValue(int value) {
    switch (value) {
      case 0: return verbatim;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_ExtraFeatures extends EnumAdapter<ExtraFeatures> {
    ProtoAdapter_ExtraFeatures() {
      super(ExtraFeatures.class, Syntax.PROTO_2, ExtraFeatures.verbatim);
    }

    @Override
    protected ExtraFeatures fromValue(int value) {
      return ExtraFeatures.fromValue(value);
    }
  }
}
