// Code generated by Wire protocol buffer compiler, do not edit.
// Source: youtubesearchfilter.Extras in youtubeFilters.proto
package org.schabi.newpipe.extractor.services.youtube.search.filter.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.ReverseProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Boolean;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class Extras extends Message<Extras, Extras.Builder> {
  public static final ProtoAdapter<Extras> ADAPTER = new ProtoAdapter_Extras();

  private static final long serialVersionUID = 0L;

  public static final Boolean DEFAULT_VERBATIM = false;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean verbatim;

  public Extras(Boolean verbatim) {
    this(verbatim, ByteString.EMPTY);
  }

  public Extras(Boolean verbatim, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.verbatim = verbatim;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.verbatim = verbatim;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Extras)) return false;
    Extras o = (Extras) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(verbatim, o.verbatim);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (verbatim != null ? verbatim.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (verbatim != null) builder.append(", verbatim=").append(verbatim);
    return builder.replace(0, 2, "Extras{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<Extras, Builder> {
    public Boolean verbatim;

    public Builder() {
    }

    public Builder verbatim(Boolean verbatim) {
      this.verbatim = verbatim;
      return this;
    }

    @Override
    public Extras build() {
      return new Extras(verbatim, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_Extras extends ProtoAdapter<Extras> {
    public ProtoAdapter_Extras() {
      super(FieldEncoding.LENGTH_DELIMITED, Extras.class, "type.googleapis.com/youtubesearchfilter.Extras", Syntax.PROTO_2, null, "youtubeFilters.proto");
    }

    @Override
    public int encodedSize(Extras value) {
      int result = 0;
      result += ProtoAdapter.BOOL.encodedSizeWithTag(1, value.verbatim);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, Extras value) throws IOException {
      ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.verbatim);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public void encode(ReverseProtoWriter writer, Extras value) throws IOException {
      writer.writeBytes(value.unknownFields());
      ProtoAdapter.BOOL.encodeWithTag(writer, 1, value.verbatim);
    }

    @Override
    public Extras decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.verbatim(ProtoAdapter.BOOL.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public Extras redact(Extras value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
