// Code generated by Wire protocol buffer compiler, do not edit.
// Source: youtubesearchfilter.Features in youtubeFilters.proto
package org.schabi.newpipe.extractor.services.youtube.search.filter.protobuf;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum Features implements WireEnum {
  is_hd(0),

  subtitles(1),

  ccommons(2),

  is_3d(3),

  live(4),

  purchased(5),

  is_4k(6),

  is_360(7),

  location(8),

  is_hdr(9);

  public static final ProtoAdapter<Features> ADAPTER = new ProtoAdapter_Features();

  private final int value;

  Features(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static Features fromValue(int value) {
    switch (value) {
      case 0: return is_hd;
      case 1: return subtitles;
      case 2: return ccommons;
      case 3: return is_3d;
      case 4: return live;
      case 5: return purchased;
      case 6: return is_4k;
      case 7: return is_360;
      case 8: return location;
      case 9: return is_hdr;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_Features extends EnumAdapter<Features> {
    ProtoAdapter_Features() {
      super(Features.class, Syntax.PROTO_2, Features.is_hd);
    }

    @Override
    protected Features fromValue(int value) {
      return Features.fromValue(value);
    }
  }
}
