// Code generated by Wire protocol buffer compiler, do not edit.
// Source: youtubesearchfilter.Filters in youtubeFilters.proto
package org.schabi.newpipe.extractor.services.youtube.search.filter.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.ReverseProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class Filters extends Message<Filters, Filters.Builder> {
  public static final ProtoAdapter<Filters> ADAPTER = new ProtoAdapter_Filters();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_DATE = 0L;

  public static final Long DEFAULT_TYPE = 0L;

  public static final Long DEFAULT_LENGTH = 0L;

  public static final Boolean DEFAULT_IS_HD = false;

  public static final Boolean DEFAULT_SUBTITLES = false;

  public static final Boolean DEFAULT_CCOMMONS = false;

  public static final Boolean DEFAULT_IS_3D = false;

  public static final Boolean DEFAULT_LIVE = false;

  public static final Boolean DEFAULT_PURCHASED = false;

  public static final Boolean DEFAULT_IS_4K = false;

  public static final Boolean DEFAULT_IS_360 = false;

  public static final Boolean DEFAULT_LOCATION = false;

  public static final Boolean DEFAULT_IS_HDR = false;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long date;

  @WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long type;

  @WireField(
      tag = 3,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long length;

  @WireField(
      tag = 4,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean is_hd;

  @WireField(
      tag = 5,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean subtitles;

  @WireField(
      tag = 6,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean ccommons;

  @WireField(
      tag = 7,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean is_3d;

  @WireField(
      tag = 8,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean live;

  @WireField(
      tag = 9,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean purchased;

  @WireField(
      tag = 14,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean is_4k;

  @WireField(
      tag = 15,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean is_360;

  @WireField(
      tag = 23,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean location;

  @WireField(
      tag = 25,
      adapter = "com.squareup.wire.ProtoAdapter#BOOL"
  )
  public final Boolean is_hdr;

  public Filters(Long date, Long type, Long length, Boolean is_hd, Boolean subtitles,
      Boolean ccommons, Boolean is_3d, Boolean live, Boolean purchased, Boolean is_4k,
      Boolean is_360, Boolean location, Boolean is_hdr) {
    this(date, type, length, is_hd, subtitles, ccommons, is_3d, live, purchased, is_4k, is_360, location, is_hdr, ByteString.EMPTY);
  }

  public Filters(Long date, Long type, Long length, Boolean is_hd, Boolean subtitles,
      Boolean ccommons, Boolean is_3d, Boolean live, Boolean purchased, Boolean is_4k,
      Boolean is_360, Boolean location, Boolean is_hdr, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.date = date;
    this.type = type;
    this.length = length;
    this.is_hd = is_hd;
    this.subtitles = subtitles;
    this.ccommons = ccommons;
    this.is_3d = is_3d;
    this.live = live;
    this.purchased = purchased;
    this.is_4k = is_4k;
    this.is_360 = is_360;
    this.location = location;
    this.is_hdr = is_hdr;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.date = date;
    builder.type = type;
    builder.length = length;
    builder.is_hd = is_hd;
    builder.subtitles = subtitles;
    builder.ccommons = ccommons;
    builder.is_3d = is_3d;
    builder.live = live;
    builder.purchased = purchased;
    builder.is_4k = is_4k;
    builder.is_360 = is_360;
    builder.location = location;
    builder.is_hdr = is_hdr;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Filters)) return false;
    Filters o = (Filters) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(date, o.date)
        && Internal.equals(type, o.type)
        && Internal.equals(length, o.length)
        && Internal.equals(is_hd, o.is_hd)
        && Internal.equals(subtitles, o.subtitles)
        && Internal.equals(ccommons, o.ccommons)
        && Internal.equals(is_3d, o.is_3d)
        && Internal.equals(live, o.live)
        && Internal.equals(purchased, o.purchased)
        && Internal.equals(is_4k, o.is_4k)
        && Internal.equals(is_360, o.is_360)
        && Internal.equals(location, o.location)
        && Internal.equals(is_hdr, o.is_hdr);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (date != null ? date.hashCode() : 0);
      result = result * 37 + (type != null ? type.hashCode() : 0);
      result = result * 37 + (length != null ? length.hashCode() : 0);
      result = result * 37 + (is_hd != null ? is_hd.hashCode() : 0);
      result = result * 37 + (subtitles != null ? subtitles.hashCode() : 0);
      result = result * 37 + (ccommons != null ? ccommons.hashCode() : 0);
      result = result * 37 + (is_3d != null ? is_3d.hashCode() : 0);
      result = result * 37 + (live != null ? live.hashCode() : 0);
      result = result * 37 + (purchased != null ? purchased.hashCode() : 0);
      result = result * 37 + (is_4k != null ? is_4k.hashCode() : 0);
      result = result * 37 + (is_360 != null ? is_360.hashCode() : 0);
      result = result * 37 + (location != null ? location.hashCode() : 0);
      result = result * 37 + (is_hdr != null ? is_hdr.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (date != null) builder.append(", date=").append(date);
    if (type != null) builder.append(", type=").append(type);
    if (length != null) builder.append(", length=").append(length);
    if (is_hd != null) builder.append(", is_hd=").append(is_hd);
    if (subtitles != null) builder.append(", subtitles=").append(subtitles);
    if (ccommons != null) builder.append(", ccommons=").append(ccommons);
    if (is_3d != null) builder.append(", is_3d=").append(is_3d);
    if (live != null) builder.append(", live=").append(live);
    if (purchased != null) builder.append(", purchased=").append(purchased);
    if (is_4k != null) builder.append(", is_4k=").append(is_4k);
    if (is_360 != null) builder.append(", is_360=").append(is_360);
    if (location != null) builder.append(", location=").append(location);
    if (is_hdr != null) builder.append(", is_hdr=").append(is_hdr);
    return builder.replace(0, 2, "Filters{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<Filters, Builder> {
    public Long date;

    public Long type;

    public Long length;

    public Boolean is_hd;

    public Boolean subtitles;

    public Boolean ccommons;

    public Boolean is_3d;

    public Boolean live;

    public Boolean purchased;

    public Boolean is_4k;

    public Boolean is_360;

    public Boolean location;

    public Boolean is_hdr;

    public Builder() {
    }

    public Builder date(Long date) {
      this.date = date;
      return this;
    }

    public Builder type(Long type) {
      this.type = type;
      return this;
    }

    public Builder length(Long length) {
      this.length = length;
      return this;
    }

    public Builder is_hd(Boolean is_hd) {
      this.is_hd = is_hd;
      return this;
    }

    public Builder subtitles(Boolean subtitles) {
      this.subtitles = subtitles;
      return this;
    }

    public Builder ccommons(Boolean ccommons) {
      this.ccommons = ccommons;
      return this;
    }

    public Builder is_3d(Boolean is_3d) {
      this.is_3d = is_3d;
      return this;
    }

    public Builder live(Boolean live) {
      this.live = live;
      return this;
    }

    public Builder purchased(Boolean purchased) {
      this.purchased = purchased;
      return this;
    }

    public Builder is_4k(Boolean is_4k) {
      this.is_4k = is_4k;
      return this;
    }

    public Builder is_360(Boolean is_360) {
      this.is_360 = is_360;
      return this;
    }

    public Builder location(Boolean location) {
      this.location = location;
      return this;
    }

    public Builder is_hdr(Boolean is_hdr) {
      this.is_hdr = is_hdr;
      return this;
    }

    @Override
    public Filters build() {
      return new Filters(date, type, length, is_hd, subtitles, ccommons, is_3d, live, purchased, is_4k, is_360, location, is_hdr, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_Filters extends ProtoAdapter<Filters> {
    public ProtoAdapter_Filters() {
      super(FieldEncoding.LENGTH_DELIMITED, Filters.class, "type.googleapis.com/youtubesearchfilter.Filters", Syntax.PROTO_2, null, "youtubeFilters.proto");
    }

    @Override
    public int encodedSize(Filters value) {
      int result = 0;
      result += ProtoAdapter.INT64.encodedSizeWithTag(1, value.date);
      result += ProtoAdapter.INT64.encodedSizeWithTag(2, value.type);
      result += ProtoAdapter.INT64.encodedSizeWithTag(3, value.length);
      result += ProtoAdapter.BOOL.encodedSizeWithTag(4, value.is_hd);
      result += ProtoAdapter.BOOL.encodedSizeWithTag(5, value.subtitles);
      result += ProtoAdapter.BOOL.encodedSizeWithTag(6, value.ccommons);
      result += ProtoAdapter.BOOL.encodedSizeWithTag(7, value.is_3d);
      result += ProtoAdapter.BOOL.encodedSizeWithTag(8, value.live);
      result += ProtoAdapter.BOOL.encodedSizeWithTag(9, value.purchased);
      result += ProtoAdapter.BOOL.encodedSizeWithTag(14, value.is_4k);
      result += ProtoAdapter.BOOL.encodedSizeWithTag(15, value.is_360);
      result += ProtoAdapter.BOOL.encodedSizeWithTag(23, value.location);
      result += ProtoAdapter.BOOL.encodedSizeWithTag(25, value.is_hdr);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, Filters value) throws IOException {
      ProtoAdapter.INT64.encodeWithTag(writer, 1, value.date);
      ProtoAdapter.INT64.encodeWithTag(writer, 2, value.type);
      ProtoAdapter.INT64.encodeWithTag(writer, 3, value.length);
      ProtoAdapter.BOOL.encodeWithTag(writer, 4, value.is_hd);
      ProtoAdapter.BOOL.encodeWithTag(writer, 5, value.subtitles);
      ProtoAdapter.BOOL.encodeWithTag(writer, 6, value.ccommons);
      ProtoAdapter.BOOL.encodeWithTag(writer, 7, value.is_3d);
      ProtoAdapter.BOOL.encodeWithTag(writer, 8, value.live);
      ProtoAdapter.BOOL.encodeWithTag(writer, 9, value.purchased);
      ProtoAdapter.BOOL.encodeWithTag(writer, 14, value.is_4k);
      ProtoAdapter.BOOL.encodeWithTag(writer, 15, value.is_360);
      ProtoAdapter.BOOL.encodeWithTag(writer, 23, value.location);
      ProtoAdapter.BOOL.encodeWithTag(writer, 25, value.is_hdr);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public void encode(ReverseProtoWriter writer, Filters value) throws IOException {
      writer.writeBytes(value.unknownFields());
      ProtoAdapter.BOOL.encodeWithTag(writer, 25, value.is_hdr);
      ProtoAdapter.BOOL.encodeWithTag(writer, 23, value.location);
      ProtoAdapter.BOOL.encodeWithTag(writer, 15, value.is_360);
      ProtoAdapter.BOOL.encodeWithTag(writer, 14, value.is_4k);
      ProtoAdapter.BOOL.encodeWithTag(writer, 9, value.purchased);
      ProtoAdapter.BOOL.encodeWithTag(writer, 8, value.live);
      ProtoAdapter.BOOL.encodeWithTag(writer, 7, value.is_3d);
      ProtoAdapter.BOOL.encodeWithTag(writer, 6, value.ccommons);
      ProtoAdapter.BOOL.encodeWithTag(writer, 5, value.subtitles);
      ProtoAdapter.BOOL.encodeWithTag(writer, 4, value.is_hd);
      ProtoAdapter.INT64.encodeWithTag(writer, 3, value.length);
      ProtoAdapter.INT64.encodeWithTag(writer, 2, value.type);
      ProtoAdapter.INT64.encodeWithTag(writer, 1, value.date);
    }

    @Override
    public Filters decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.date(ProtoAdapter.INT64.decode(reader)); break;
          case 2: builder.type(ProtoAdapter.INT64.decode(reader)); break;
          case 3: builder.length(ProtoAdapter.INT64.decode(reader)); break;
          case 4: builder.is_hd(ProtoAdapter.BOOL.decode(reader)); break;
          case 5: builder.subtitles(ProtoAdapter.BOOL.decode(reader)); break;
          case 6: builder.ccommons(ProtoAdapter.BOOL.decode(reader)); break;
          case 7: builder.is_3d(ProtoAdapter.BOOL.decode(reader)); break;
          case 8: builder.live(ProtoAdapter.BOOL.decode(reader)); break;
          case 9: builder.purchased(ProtoAdapter.BOOL.decode(reader)); break;
          case 14: builder.is_4k(ProtoAdapter.BOOL.decode(reader)); break;
          case 15: builder.is_360(ProtoAdapter.BOOL.decode(reader)); break;
          case 23: builder.location(ProtoAdapter.BOOL.decode(reader)); break;
          case 25: builder.is_hdr(ProtoAdapter.BOOL.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public Filters redact(Filters value) {
      Builder builder = value.newBuilder();
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
