// Code generated by Wire protocol buffer compiler, do not edit.
// Source: youtubesearchfilter.LenFilter in youtubeFilters.proto
package org.schabi.newpipe.extractor.services.youtube.search.filter.protobuf;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum LenFilter implements WireEnum {
  duration_short(1),

  duration_long(2);

  public static final ProtoAdapter<LenFilter> ADAPTER = new ProtoAdapter_LenFilter();

  private final int value;

  LenFilter(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static LenFilter fromValue(int value) {
    switch (value) {
      case 1: return duration_short;
      case 2: return duration_long;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_LenFilter extends EnumAdapter<LenFilter> {
    ProtoAdapter_LenFilter() {
      super(LenFilter.class, Syntax.PROTO_2, null);
    }

    @Override
    protected LenFilter fromValue(int value) {
      return LenFilter.fromValue(value);
    }
  }
}
