// Code generated by Wire protocol buffer compiler, do not edit.
// Source: youtubesearchfilter.SearchRequest in youtubeFilters.proto
package org.schabi.newpipe.extractor.services.youtube.search.filter.protobuf;

import com.squareup.wire.FieldEncoding;
import com.squareup.wire.Message;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.ProtoReader;
import com.squareup.wire.ProtoWriter;
import com.squareup.wire.ReverseProtoWriter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireField;
import com.squareup.wire.internal.Internal;
import java.io.IOException;
import java.lang.Long;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.StringBuilder;
import okio.ByteString;

public final class SearchRequest extends Message<SearchRequest, SearchRequest.Builder> {
  public static final ProtoAdapter<SearchRequest> ADAPTER = new ProtoAdapter_SearchRequest();

  private static final long serialVersionUID = 0L;

  public static final Long DEFAULT_SORTED = 0L;

  @WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#INT64"
  )
  public final Long sorted;

  @WireField(
      tag = 2,
      adapter = "org.schabi.newpipe.extractor.services.youtube.search.filter.protobuf.Filters#ADAPTER"
  )
  public final Filters filter;

  @WireField(
      tag = 8,
      adapter = "org.schabi.newpipe.extractor.services.youtube.search.filter.protobuf.Extras#ADAPTER"
  )
  public final Extras extras;

  public SearchRequest(Long sorted, Filters filter, Extras extras) {
    this(sorted, filter, extras, ByteString.EMPTY);
  }

  public SearchRequest(Long sorted, Filters filter, Extras extras, ByteString unknownFields) {
    super(ADAPTER, unknownFields);
    this.sorted = sorted;
    this.filter = filter;
    this.extras = extras;
  }

  @Override
  public Builder newBuilder() {
    Builder builder = new Builder();
    builder.sorted = sorted;
    builder.filter = filter;
    builder.extras = extras;
    builder.addUnknownFields(unknownFields());
    return builder;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof SearchRequest)) return false;
    SearchRequest o = (SearchRequest) other;
    return unknownFields().equals(o.unknownFields())
        && Internal.equals(sorted, o.sorted)
        && Internal.equals(filter, o.filter)
        && Internal.equals(extras, o.extras);
  }

  @Override
  public int hashCode() {
    int result = super.hashCode;
    if (result == 0) {
      result = unknownFields().hashCode();
      result = result * 37 + (sorted != null ? sorted.hashCode() : 0);
      result = result * 37 + (filter != null ? filter.hashCode() : 0);
      result = result * 37 + (extras != null ? extras.hashCode() : 0);
      super.hashCode = result;
    }
    return result;
  }

  @Override
  public String toString() {
    StringBuilder builder = new StringBuilder();
    if (sorted != null) builder.append(", sorted=").append(sorted);
    if (filter != null) builder.append(", filter=").append(filter);
    if (extras != null) builder.append(", extras=").append(extras);
    return builder.replace(0, 2, "SearchRequest{").append('}').toString();
  }

  public static final class Builder extends Message.Builder<SearchRequest, Builder> {
    public Long sorted;

    public Filters filter;

    public Extras extras;

    public Builder() {
    }

    public Builder sorted(Long sorted) {
      this.sorted = sorted;
      return this;
    }

    public Builder filter(Filters filter) {
      this.filter = filter;
      return this;
    }

    public Builder extras(Extras extras) {
      this.extras = extras;
      return this;
    }

    @Override
    public SearchRequest build() {
      return new SearchRequest(sorted, filter, extras, super.buildUnknownFields());
    }
  }

  private static final class ProtoAdapter_SearchRequest extends ProtoAdapter<SearchRequest> {
    public ProtoAdapter_SearchRequest() {
      super(FieldEncoding.LENGTH_DELIMITED, SearchRequest.class, "type.googleapis.com/youtubesearchfilter.SearchRequest", Syntax.PROTO_2, null, "youtubeFilters.proto");
    }

    @Override
    public int encodedSize(SearchRequest value) {
      int result = 0;
      result += ProtoAdapter.INT64.encodedSizeWithTag(1, value.sorted);
      result += Filters.ADAPTER.encodedSizeWithTag(2, value.filter);
      result += Extras.ADAPTER.encodedSizeWithTag(8, value.extras);
      result += value.unknownFields().size();
      return result;
    }

    @Override
    public void encode(ProtoWriter writer, SearchRequest value) throws IOException {
      ProtoAdapter.INT64.encodeWithTag(writer, 1, value.sorted);
      Filters.ADAPTER.encodeWithTag(writer, 2, value.filter);
      Extras.ADAPTER.encodeWithTag(writer, 8, value.extras);
      writer.writeBytes(value.unknownFields());
    }

    @Override
    public void encode(ReverseProtoWriter writer, SearchRequest value) throws IOException {
      writer.writeBytes(value.unknownFields());
      Extras.ADAPTER.encodeWithTag(writer, 8, value.extras);
      Filters.ADAPTER.encodeWithTag(writer, 2, value.filter);
      ProtoAdapter.INT64.encodeWithTag(writer, 1, value.sorted);
    }

    @Override
    public SearchRequest decode(ProtoReader reader) throws IOException {
      Builder builder = new Builder();
      long token = reader.beginMessage();
      for (int tag; (tag = reader.nextTag()) != -1;) {
        switch (tag) {
          case 1: builder.sorted(ProtoAdapter.INT64.decode(reader)); break;
          case 2: builder.filter(Filters.ADAPTER.decode(reader)); break;
          case 8: builder.extras(Extras.ADAPTER.decode(reader)); break;
          default: {
            reader.readUnknownField(tag);
          }
        }
      }
      builder.addUnknownFields(reader.endMessageAndGetUnknownFields(token));
      return builder.build();
    }

    @Override
    public SearchRequest redact(SearchRequest value) {
      Builder builder = value.newBuilder();
      if (builder.filter != null) builder.filter = Filters.ADAPTER.redact(builder.filter);
      if (builder.extras != null) builder.extras = Extras.ADAPTER.redact(builder.extras);
      builder.clearUnknownFields();
      return builder.build();
    }
  }
}
