// Code generated by Wire protocol buffer compiler, do not edit.
// Source: youtubesearchfilter.SortOrder in youtubeFilters.proto
package org.schabi.newpipe.extractor.services.youtube.search.filter.protobuf;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum SortOrder implements WireEnum {
  relevance(0),

  rating(1),

  date(2),

  views(3);

  public static final ProtoAdapter<SortOrder> ADAPTER = new ProtoAdapter_SortOrder();

  private final int value;

  SortOrder(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static SortOrder fromValue(int value) {
    switch (value) {
      case 0: return relevance;
      case 1: return rating;
      case 2: return date;
      case 3: return views;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_SortOrder extends EnumAdapter<SortOrder> {
    ProtoAdapter_SortOrder() {
      super(SortOrder.class, Syntax.PROTO_2, SortOrder.relevance);
    }

    @Override
    protected SortOrder fromValue(int value) {
      return SortOrder.fromValue(value);
    }
  }
}
