// Code generated by Wire protocol buffer compiler, do not edit.
// Source: youtubesearchfilter.TypeFilter in youtubeFilters.proto
package org.schabi.newpipe.extractor.services.youtube.search.filter.protobuf;

import com.squareup.wire.EnumAdapter;
import com.squareup.wire.ProtoAdapter;
import com.squareup.wire.Syntax;
import com.squareup.wire.WireEnum;
import java.lang.Override;

public enum TypeFilter implements WireEnum {
  video(1),

  channel(2),

  playlist(3),

  movie(4),

  show(5);

  public static final ProtoAdapter<TypeFilter> ADAPTER = new ProtoAdapter_TypeFilter();

  private final int value;

  TypeFilter(int value) {
    this.value = value;
  }

  /**
   * Return the constant for {@code value} or null.
   */
  public static TypeFilter fromValue(int value) {
    switch (value) {
      case 1: return video;
      case 2: return channel;
      case 3: return playlist;
      case 4: return movie;
      case 5: return show;
      default: return null;
    }
  }

  @Override
  public int getValue() {
    return value;
  }

  private static final class ProtoAdapter_TypeFilter extends EnumAdapter<TypeFilter> {
    ProtoAdapter_TypeFilter() {
      super(TypeFilter.class, Syntax.PROTO_2, null);
    }

    @Override
    protected TypeFilter fromValue(int value) {
      return TypeFilter.fromValue(value);
    }
  }
}
